name: demo_ecom
description: Demo Ecom App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.9.0-8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Service locator
  rxdart: ^0.26.0
  provider: ^5.0.0

  # Connectivity
  data_connection_checker: ^0.3.4
  # Logging
  logger: ^1.0.0
  # Json
  json_annotation: ^4.0.1

  # firebase
  firebase_core: ^0.7.0
  firebase_remote_config: "^0.6.0"
  firebase_auth: "^0.20.1"
  firebase_crashlytics: ^0.4.0+1

  # localization
  intl: ^0.17.0
  # ui tools
  flutter_signin_button: ^1.1.0
  animations: ^2.0.0
  pull_to_refresh: ^1.6.4
  get: ^3.26.0
  flutter_easyloading: ^3.0.0
  responsive_framework: ^0.1.0
  animated_text_kit: ^4.1.0
  convex_bottom_bar: ^3.0.0
  introduction_screen: ^2.0.0
  flash: ^1.5.1
  material_floating_search_bar: ^0.3.3
  video_player: ^2.1.0
  chewie: ^1.0.0
  # ui icons

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  flutter_icons: ^1.1.0

  # misc tools
  validators: ^2.0.1
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1
  jiffy: ^4.0.0
  equatable: ^2.0.0
  meta: ^1.3.0
  data_channel: ^1.0.4+1
  stack_trace: ^1.10.0
  shared_preferences: ^2.0.5
# override requirement that conflict will rise if removed
dependency_overrides:
  analyzer: ^1.3.0
  yaml: ^3.1.0
  intl: ^0.17.0
  dart_style: ^2.0.0
  args: ^2.0.0
  glob: ^2.0.0
  source_gen: ^1.0.0
  logging: ^1.0.1
  convert: ^3.0.0
  crypto: ^3.0.0
  vin_decoder: ^0.1.3
  json_annotation: ^4.0.1
  font_awesome_flutter: ^9.0.0
dev_dependencies:
  # add build runner if not already added
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  # Linting
  lint: ^1.5.3

  # Json
  json_serializable: ^4.1.0

  # misc tools
  mockito: ^5.0.2
  flutter_launcher_icons: ^0.9.0
  environment_config: ^2.2.5
  flutter_rename_app: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/media/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-package

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
flutter_intl:
  enabled: true
  localizely:
    project_id: c4305176-c927-4336-80bd-7bbc91f25b3d
flutter_icons:
  image_path: 'assets/assets/icons/app_icon.png'
  android: true
  ios: true

flutter_rename_app:
  application_name: Demo Ecom
  dart_package_name: demo_ecom
  application_id: com.wolberg.pro.demo
  bundle_id: com.wolberg.pro.demo
  android_package_name: com.wolberg.pro.demo
targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # auto registers any class with a name matches the given pattern
          class_name_pattern:
            "Service$|Repository$"
            # auto registers any class inside a file with a
          # name matches the given pattern
          file_name_pattern: "_service$|_repository$"
#flutter pub run flutter_rename_app