name: demo_ecom
description: Demo Ecom App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Service locator
  rxdart: ^0.26.0
  provider: ^5.0.0

  # Connectivity
  # Logging
  logger: ^1.0.0
  # Json
  json_annotation: ^4.0.0
  # graphql staff
  graphql_flutter: ^5.0.0-nullsafety.2
  # firebase
  firebase_core: ^1.0.2
  firebase_remote_config: ^0.9.0-dev.1
  firebase_auth: ^1.0.1
  firebase_crashlytics: ^1.0.0
  cloud_firestore: ^1.0.4
  #  firebase_analytics: ^7.1.1

  #auth social
  google_sign_in: ^5.0.2
  flutter_facebook_auth: ^3.3.3+1
  # localization
  intl: ^0.17.0
  # ui tools
  flutter_password_strength: ^0.1.6
  flutter_signin_button: ^2.0.0
  animations: ^2.0.0
  # pull_to_refresh: ^1.6.4
  get: ^4.1.4
  #  responsive_framework: ^0.1.0
  # animated_text_kit: ^4.1.0
  # convex_bottom_bar: ^3.0.0
  introduction_screen: ^2.1.0
  # flash: ^1.5.1
  # material_floating_search_bar: ^0.3.3
  # ui icons

  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0

  # misc tools
  validators:
    git: https://github.com/dart-league/validators.git
  equatable: ^2.0.0
  meta: ^1.3.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.3
  flutter_overlay_loader: ^0.1.1
  dart_extensions: ^2.0.4
#  async: ^2.5.0
# override requirement that conflict will rise if removed
dependency_overrides:
  analyzer: ^1.4.0
  dart_style: ^2.0.0
  yaml: ^3.1.0
  args: ^2.0.0
  web_socket_channel: ^2.0.0
  # source_gen: ^1.0.0
  crypto: ^3.0.0
dev_dependencies:
  # add build runner if not already added
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  # Linting
  lint: ^1.5.3
  # Json
  json_serializable: ^4.0.0

  # misc tools
  mockito: ^5.0.2
  flutter_launcher_icons: ^0.9.0
  environment_config: ^2.2.5
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/media/
    - assets/icons/

flutter_intl:
  enabled: true
  localizely:
    project_id: c4305176-c927-4336-80bd-7bbc91f25b3d
flutter_icons:
  image_path: 'assets/icons/app_icon.png'
  android: true
  ios: true