name: demo_ecom
description: Demo Ecom App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Service locator
  provider: ^5.0.0

  # Connectivity
  # Logging
  logger: ^1.0.0
  # Json
  json_annotation: ^4.0.1

  # firebase
  firebase_core: ^1.0.2
  firebase_remote_config: ^0.9.0-dev.1
  firebase_auth: ^1.0.1
  firebase_crashlytics: ^1.0.0
#  firebase_analytics: ^7.1.1

  #auth social
  google_sign_in: ^5.0.1
  flutter_facebook_auth: ^3.3.2
  # localization
  intl: ^0.17.0
  # ui tools
  flutter_password_strength: ^0.1.6
  flutter_signin_button: ^2.0.0
  animations: ^2.0.0
  # pull_to_refresh: ^1.6.4
  get: ^4.1.2
#  responsive_framework: ^0.1.0
  # animated_text_kit: ^4.1.0
  # convex_bottom_bar: ^3.0.0
  introduction_screen: ^2.0.0
  # flash: ^1.5.1
  # material_floating_search_bar: ^0.3.3
  video_player: ^2.1.0
  # ui icons

  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0

  # misc tools
  validators:
    git: https://github.com/dart-league/validators.git
  http_parser: ^4.0.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  equatable: ^2.0.0
  meta: ^1.3.0
  shared_preferences: ^2.0.5
#  async: ^2.5.0
# override requirement that conflict will rise if removed
dependency_overrides:
  dart_style: ^2.0.0
  yaml: ^3.1.0
  args: ^2.0.0
  source_gen: ^1.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
dev_dependencies:
  # add build runner if not already added
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  # Linting
  lint: ^1.5.3

  # Json
  json_serializable: ^4.1.0

  # misc tools
  mockito: ^5.0.2
  flutter_launcher_icons: ^0.9.0
  environment_config: ^2.2.5
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/media/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-package

flutter_intl:
  enabled: true
  localizely:
    project_id: c4305176-c927-4336-80bd-7bbc91f25b3d
flutter_icons:
  image_path: 'assets/icons/app_icon.png'
  android: true
  ios: true
#flutter pub run flutter_rename_app